generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ExportHistory
    theme:            default
    label_singular:   Export
    label_plural:     Exports
    parents:
      schema:         { getid: schema_id, requestid: schema_id }
      vocabulary:     { getid: vocabulary_id, requestid: vocabulary_id }
    pager:
      no_results:     There have been no Exports

    fields:
      id:             { name: ID, type: plain}
      created_at:     { name: Date Created, type: plain, params: date_format='s', help: This is the date the export was created }
      user:           { name: Member, type: plain, help: The individual that created the export }
      csv_type:
        name: CSV Type
        help: The type of CSV file to export
      csv_type_to_string:
        name: CSV Type
      exclude_deprecated:   { name: Exclude Deprecated, type: checkbox_tag, help: This will exclude from the export currently deprecated elements }
      exclude_generated:    { name: Exclude Generated, type: checkbox_tag, help: This will exclude from the export inferred elements materialized by the Registry }
      include_deleted:
        name: Include Deleted
        type: checkbox_tag
        help: |
          This will include most of the previously deleted element properties in the export.
          This isn't a complete 'undo' feature. It simply puts properties that have been deleted back in the exported data.
          It's primary utility is to recover properties that were deleted by misteak in the last import.
        credentials: [subscriber]
      include_not_accepted:
        name: Include not 'Published'
        type: checkbox_tag
        help: |
          This will include Resources in the export that have a status other than 'Published'.
          The default is to ONLY export published Resources, and this will override that.
      selected_language:
        name: Additional Language
        help: |
          The default language is English
          Additional language column included for populating each literal attribute
      selected_columns_to_string: {name: Selected Columns}

      selected_columns: { name: Selected Columns}
      published_english_version:  { name: English Version, type: plain, help: The published English version on which this export is based  }
      published_language_version:  { name: Language Version, type: plain, help: The published version of the selected language on which this export is based }
      last_vocab_update:  { name: Last Update, type: plain, params: date_format='s', help: The date of the last update of this vocabulary  }

    list:
      title:          Export History
      fields:
        created_at:   { params: date_format='F' }
      display:        [created_at, user, csv_type_to_string, _selected_language, published_english_version, published_language_version]
      sort:           [created_at, desc]
      displayfilter:  false
      filters:        [schema_id, created_at, user_id, vocabulary_id]
      # urlfilter form is [field to filter on]: [value passed from routing.yml]
      # multiple filters can be set but they're currently mutually exclusive (any of the list can be used but only one per url)
      urlfilters:
        schema_id:                  schema_id
        vocabulary_id:              vocabulary_id
      object_actions:
        _show:
      actions:
        - _create:       { name: Create New Export, query_string: { sf_request: vocabulary_id}, condition: "!$sf_request->getParameter('schema_id')", route: "vocabulary_export_create" }
        - _create:       { name: Create New Export, query_string: { sf_request: schema_id}, condition: "!$sf_request->getParameter('vocabulary_id')", route: "schema_export_create" }

    edit:
      title:
        mode:
          edit:       Editing
          create:     Create a new CSV export
      helptype:       icon
      fields:
        id:           { credentials: [administrator], mode: edit }
        selected_language:
          type:       admin_select_language
          condition:  "$sf_flash->get('hasLanguages')"
          params:     { include_blank: true, limitmethod: getLanguagesNoDefault }
        selected_columns:
          type:       select_tag
          params:
            array_method: getProfileColumns
            related_class: ExportHistory
            multiple: multiple
          help: |
            Select the columns that will be in the exported CSV. Required columns will always be selected for you.
            You may also drag and drop the columns to change the order.
            The columns you select, and their order, will be saved for the next time you create an export.
        save_as_default:   { name: Save as my default, type: checkbox_tag, help: Save these settings as my default settings for future exports, credentials: [subscriber] }

      display:        [id, selected_columns, selected_language, exclude_deprecated, exclude_generated, include_deleted, include_not_accepted  ]
      hide:           [schema_id, user_id, vocabulary_id]
      actions:
        _save:         { name: Export CSV }
        _cancel:       { name: Cancel  }
      urlfilters:
        agent_id:      schema_id
        vocabulary_id: vocabulary_id

    show:
      fields:
        id:            { credentials: [administrator] }
#        map:           { helper: auto_link_uri }
#        results:       { helper: auto_link_text }
        created_at:    { params: date_format='F' }
        _elapsed:      { name: Elapsed }
      display:
        "Import Detail":      [created_at, user]
        "Results":            [csv_type_to_string, _selected_language, selected_columns_to_string, exclude_deprecated, exclude_generated, include_deleted, include_not_accepted, published_english_version, published_language_version, last_vocab_update ]
#        "Map":                [map]
      actions:
        _list:

