editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2, %sf_jqwidgets_web_dir%/styles/jqx.base.css]
  javascripts: [vocabulary: { position: last }, %sf_jquery_web_dir%/jquery, %sf_select2_web_dir%/select2 ]
