language: php

php:
  - 7.1
#  - hhvm
#  - hhvm-nightly
env:
  matrix:
  - NO_GOOGLE=TRUE
# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - env: NO_GOOGLE=TRUE
#    - php: hhvm-nightly

# cache vendor dirs
cache:
  yarn: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - chmod +x ./scripts/* #thanks https://medium.com/@psaunders
  - ./scripts/travis_mysql_5.7.sh
  - ./scripts/mysql-reset-root-password.sh
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=0.24.4-1
  - cp .env.travis .env
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - nvm install stable
  - nvm use stable

install:
#  - npm install
# codeception
#  - travis_retry composer global require "codeception/codeception=2.2.*" "codeception/specify=*" "codeception/verify=*"
  - yarn
  - npm install bower
#  - bower install
  - npm run production
# setup application:
#  - |
#    cd tests
#    codecept build
#    cd ..
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -u root -e 'create database swregistry_test;'
  - php artisan migrate -vvv --seed --force
  - php artisan key:generate

script:
  - vendor/bin/phpunit --configuration phpunit.xml

# whitelist
branches:
  only:
    - beta
after_failure:
  - cat storage/logs/laravel-`date +"%Y-%m-%d"`.log
