language: php

php:
  - 7.1
#  - hhvm
#  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
#    - php: hhvm-nightly

# cache vendor dirs
cache:
  yarn: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - chmod +x ./scripts/* #thanks https://medium.com/@psaunders
  - ./scripts/travis_mysql_5.7.sh
  - ./scripts/mysql-reset-root-password.sh
  - cp .env.travis .env
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - nvm install 7.6
  - nvm use 7.6

install:
  - npm install
# codeception
#  - travis_retry composer global require "codeception/codeception=2.2.*" "codeception/specify=*" "codeception/verify=*"
#  - yarn
  - npm install bower
#  - bower install
  - gulp --production
# setup application:
#  - |
#    cd tests
#    codecept build
#    cd ..
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -u root -e 'create database swregistry_test;'
  - php artisan migrate -vvv --seed --force
  - php artisan key:generate

script:
  - vendor/bin/phpunit --configuration phpunit.xml

# whitelist
branches:
  only:
    - beta
    - new_tabs
