generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      VocabularyHasUser
    theme:            default
    fields:
      id:                { name: ID, type: plain, credentials: [administrator] }
      created_at:        { name: Date Created, type: plain, credentials: [administrator] }
      updated_at:        { name: Last Updated, type: plain, credentials: [administrator] }
      is_admin_for:      { name: Administrator }
      is_registrar_for:  { name: Registrar }
      is_maintainer_for: { name: Maintainer }
      languages:         { name: Editable Languages }
      default_language:  { name: Default Language }

    list:
      #peer_method:       doSelectJoinAll
      #peer_count_method: doCountForUser
      title:              Maintainers for %%vocabulary%%
      display:            [_member, _vocabulary, isRegistrarFor, isAdminFor, isMaintainerFor, _languages, _defaultLanguage]
      object_actions:
        _show:
        _edit:            { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _delete:          { credentials: [[administrator, vocabularyadmin, agentadmin]] }
      actions:
        _create:          {query_string: {vocabulary_id: vocabulary_id}, name: Add Maintainer, credentials: [[administrator, vocabularyadmin, agentadmin]] }
      displayfilter:      false
      filters:            [vocabulary_id, user_id]
      urlfilters:
        vocabulary_id:    vocabulary_id
        user_id:          user_id

    edit:
      title:
        mode:
          edit:       Editing “%%vocabulary%%” permissions for %%user%%
          create:     Adding maintainer to “%%vocabulary%%”
      helptype:       icon
      fields:
        user_id:       { params: peer_method=getNewUsersForVocabulary include_blank=false, mode: create }
        user:          { type: plain, mode: edit }
        is_registrar_for:  { credentials: [[administrator]], mode: edit}
        languages:         { type: admin_select_language, params: multiple=true limitmethod=getLanguagesForVocabulary style="width:99%" include_custom=[*, All languages ], credentials: [[administrator, vocabularyadmin, agentadmin]] }
        default_language:  { type: admin_select_language, params: limitmethod=getLanguagesForVocabulary style="width:99%", credentials: [[administrator, vocabularyadmin, agentadmin]] }
      display:         [user, user_id, isRegistrarFor, isAdminFor, isMaintainerFor, languages, default_language]
      actions:
        _save:         { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _delete:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _save_and_add: { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _cancel:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }

    show:
      title:           %%vocabulary%% permissions for %%user%%
      fields:
        user:          { type: plain }
      display:         [user, isRegistrarFor, isAdminFor, isMaintainerFor, _languages, _defaultLanguage]
      actions:
        _list:
        _delete:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _edit:         { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _create:       { name: Add Maintainer, credentials: [[administrator, vocabularyadmin, agentadmin]] }
      urlfilters:
        vocabulary_id:    vocabulary_id
        user_id:          user_id
