default:
  http_metas:
    content-type:       text/html; charset=utf-8

  metas:
    title:        The Registry Project
    robots:       index,follow
    description:  The Metadata Registry Project
    keywords:     semantic web, registry, rdf, skos, metadata
    google-site-verification: Y6w7paanRUDHHWWKN9NXAtbDWP3ftC0yDYKwyiFmnzo

  stylesheets:    [main, layout, ui]

  javascripts:    []

  has_layout:     on
  layout:         layout
  components:
    sidebar:      [sidebar, default]
    tabnav:       [tabnav, default]

  use_default_slots: on
