generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      User
    theme:            default

    fields:
      id:             { name: ID, type: plain, credentials: [administrator] }
      created_at:     { name: Date Created, type: plain, credentials: [administrator] }
      updated_at:   { name: Last Updated, type: plain, credentials: [administrator] }
      nickname:       { name: Login Name }
      salutation:     { name: Salutation }
      first_name:     { name: First Name }
      last_name:      { name: Last Name }
      email:          { name: Email }
      password:       { name: Password }
      is_administrator:     { name: Administrator }

    list:
      title:           Members
      fields:
        user:          { credentials: [administrator] }
      display:         [user, =nickname, last_name, first_name]
      object_actions:
         _edit:        { credentials: [administrator, useradmin] }
      actions:
        _create:       { credentials: [administrator] }

    edit:
      title:           Detail for %%user%%
      display:
        "-Metadata":
          fields:      [id, created_at, updated_at]
          mode:        edit
          credentials: [administrator]
        "Detail":      [nickname, salutation, first_name, last_name, email]
      actions:
#        _list:      -
        _save:         { credentials: [administrator, useradmin] }
        _delete:       { credentials: [administrator] }
        _create:       { credentials: [administrator] }
        _save_and_add: { credentials: [administrator] }

    show:
      fields:
        vocabulary_list: { name: " " }
        agent_list:      { name: " " }
        email:           { credentials: [administrator]}
      display:
        "-Metadata":    [id, created_at, updated_at]
        "Detail":       [nickname, salutation, first_name, last_name, email]
      actions:
        _edit:         { credentials: [administrator, useradmin] }
