passwordRequestMailSent:
  javascripts: [-*]

all:
  javascripts: [%sf_jquery_web_dir%/jquery.min.js]
  stylesheets: [../jpAdminPlugin/css/main]

editSuccess:
  javascripts: [setfocus: { position: last }]
