passwordRequestMailSent:
  javascripts: [-*]

all:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/prototype.min.js: { position: last }]
  stylesheets: [../jpAdminPlugin/css/main]

editSuccess:
  javascripts: [setfocus: { position: last }]
