generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ProfileProperty
    theme:            default

    list:
      filters:        [profile_id]
      urlfilters:
        profile_id:    profile_id
