all:
  stylesheets: [conceptprop/layout]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/prototype.min.js: { position: last }]

editSuccess:
  javascripts: [conceptprop/swapoptions: { position: last }]

searchSuccess:
  stylesheets: -*
