all:
  stylesheets: [conceptprop/layout]
  javascripts: [%sf_jquery_web_dir%/jquery.min.js]

editSuccess:
  javascripts: [conceptprop/swapoptions: { position: last }]

searchSuccess:
  stylesheets: -*
