generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Agent
    theme:            default

    fields:
      id:             { name: ID }
      created_at:     { name: Date Created }
      last_updated:   { name: Last Updated }
      org_name:       { name: Project Name}
      repo:           { name: GitHub Repository}
      is_private:     { name: Private}

    list:
      title:           Projects
      display:         [=org_name, created_at, is_private]
      actions:
        _create:       { name: Add Project, credentials: [subscriber], route: agent_create }
      object_actions:
        _edit:         { credentials: [[administrator, agentadmin]] }

    edit:
      title:
        mode:
          edit:        Editing %%org_name%%
          create:      Creating new Project
      display:
        "Detail":      [org_name, repo, is_private]
      actions:
#        _list:         -
        _save:         { credentials: [[administrator, agentadmin]] } #for a single object, object and general credentials are merged
        _delete:       { credentials: [administrator] }
        _save_and_add: { credentials: [administrator] }
        _cancel:       { route: homepage, credentials: [[administrator, agentadmin]] }

    show:
      fields:
        id:           { type: plain, credentials: [administrator] }
        created_at:   { type: plain }
        last_updated: { type: plain }
      display:
        "-Metadata":   { fields: [id, created_at, last_updated], credentials: [[administrator, agentadmin]] }
        "Detail":     [org_name, repo, is_private]
      actions:
#        _list:        -
        _edit:        { credentials: [[administrator, agentadmin]] }
