all:
  stylesheets: [vocabulary/layout, tabs]
#  javascripts: [%SF_PROTOTYPE_WEB_DIR%/prototype.min.js: { position: last }]
editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2]
  javascripts: [vocabulary: { position: last }, %sf_jquery_web_dir%/jquery, %sf_select2_web_dir%/select2 ]
