test:
  propel:
    param:
      database:           swregistry_test
dev:
  propel:
    param:
      host:               localhost
      database:           swregistry
      username:           root
      password:           RegIt!
sandbox:
  propel:
    param:
      database:           swregistry_sandbox

prod:
  propel:
    param:
      database:           swregistry
all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            mysql
      host:               localhost
      database:           swregistry
      username:           root
      password:           RegIt!
      compat_assoc_lower: true
      datasource:         propel

