all:
  is_secure:  off

create:
  is_secure:   on
  credentials: [[administrator, hasAgents]]

edit:
  is_secure:   on
  credentials: [[administrator, schemaadmin]]

publish:
  is_secure:   on
  credentials: [[administrator, schemaadmin]]
