editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2, /js/components/sweetalert2/dist/sweetalert2.css]
  javascripts: [schema: { position: last }, %sf_jquery_web_dir%/jquery.min.js, %sf_select2_web_dir%/select2, /js/components/sweetalert2/dist/sweetalert2.min.js]

exportSuccess:
  stylesheets: [%sf_select2_web_dir%/select2]
  javascripts: [export: { position: last }, components/jquery/dist/jquery.min.js, %sf_select2_web_dir%/select2]

showRdfSuccess:
  has_layout: off
  http_metas:
    content-type: application/rdf+xml; charset="utf-8"

getCsvSuccess:
  has_layout: off
  http_metas:
    content-type: text/csv; charset="utf-8"

