all:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype: { position: last }]

editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2/select2]
  javascripts: [schema: { position: last }, %sf_select2_web_dir%/jquery/dist/jquery, %sf_select2_web_dir%/select2/select2]

showRdfSuccess:
  has_layout: off
  http_metas:
    content-type: application/rdf+xml; charset="utf-8"
