all:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/prototype.min.js: { position: last }]

editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2]
  javascripts: [schema: { position: last }, components/jquery/dist/jquery.min.js, %sf_select2_web_dir%/select2]

exportSuccess:
  stylesheets: [%sf_select2_web_dir%/select2]
  javascripts: [export: { position: last }, components/jquery/dist/jquery.min.js, %sf_select2_web_dir%/select2]

showRdfSuccess:
  has_layout: off
  http_metas:
    content-type: application/rdf+xml; charset="utf-8"

getCsvSuccess:
  has_layout: off
  http_metas:
    content-type: text/csv; charset="utf-8"

