all:
  stylesheets: [concept/layout, tabs]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/prototype.min.js: { position: last }]

editSuccess:
  stylesheets: [%sf_select2_web_dir%/select2/select2]
  javascripts: [schemaprop/swapoptions: { position: last }, schemaprop: { position: last }, %sf_select2_web_dir%/jquery/dist/jquery: { position: first }, %sf_select2_web_dir%/select2/select2: { position: first } ]

showRdfSuccess:
  has_layout: off
  http_metas:
    content-type: application/rdf+xml; charset="utf-8"
